spring.application.name=spring-playground

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_playground
spring.datasource.username=usr_pg
spring.datasource.password=pg_password
logging.level.org.springframework.security=DEBUG