spring.config.import=optional:file:.env[.properties]
server.port=${APP_PORT:8080}

spring.application.name=${APP_NAME:spring-playground}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:spring_playground}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
logging.level.org.springframework.security=${APP_LOGGING:DEBUG}
spring.web.error.include-stacktrace=never